apiVersion: apps/v1beta1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: domain-model-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        application: domain-model-service-v1
        version: v1
    spec:
      containers:
      - name: domain-model-service-v1
        image: consortit-docker-cme-local.jfrog.io/domain-model-service:image-version
        ports:
        - containerPort: 8080
        - containerPort: 8081
        env:
        - name: gitlab_adapter_url
          valueFrom:
            secretKeyRef:
              name: domain-model-service-secret
              key: gitlab_adapter_url
        - name: accesskey_s3
          valueFrom:
            secretKeyRef:
              name: domain-model-service-secret
              key: accesskey
        - name: secretkey_s3
          valueFrom:
            secretKeyRef:
              name: domain-model-service-secret
              key: secretkey
        - name: jwk_kid
          valueFrom:
            secretKeyRef:
              name: domain-model-service-secret
              key: jwk_kid
        - name: appname
          value: domain-model-service
        - name: bucket_name
          value: cme2-domain-model-service
        - name: appversion
          value: "0.1"
        - name: jwk_url
          value: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_M4FyC0JPA/.well-known/jwks.json
        - name: jwk_alg
          value: RS256
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  name: domain-model-service-v1
  labels:
    application: domain-model-service-v1
    version: v1
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: external
    - port: 81
      protocol: TCP
      targetPort: 8081
      name: external2
  selector:
    application: domain-model-service-v1
    version: v1
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: domain-model-service-v1
  labels:
    application: domain-model-service-v1
spec:
  rules:
  - host: "cme.dev.k8s.consort-it.de"
    http:
      paths:
      - path: /api/v1/domain-model-service/models
        backend:
          serviceName: domain-model-service-v1
          servicePort: 80
      - path: /api/v1/domain-model-service/health
        backend:
          serviceName: domain-model-service-v1
          servicePort: 81
      - path: /api/v1/domain-model-service/metrics
        backend:
          serviceName: domain-model-service-v1
          servicePort: 81
          
          
          
