swagger: "2.0"
info:
  description: "This is the domain model service of consort-group. It returns all objects defined in the corresponding swagger files."
  version: "1.0.0"
  title: "domain-model-service"
  contact:
    email: "dev@consort-it.de"
basePath: "/api/v1/domain-model-service"
schemes:
- "https"
paths:
  /models/{projectName}:
    parameters:
    - name: "projectName"
      in: path
      description: "The name of the project for which we want to store our additional properties"
      required: true
      type: string
    - name: "serviceNames"
      in: "query"
      description: "The names of the services whose objects are requested"
      required: true
      type: "array"
      items:
        type: string
      collectionFormat: "csv"
    get:
      operationId: "getModelsForServices"
      tags:
        - "DomainModelBackend"
      summary: "Get the model objects defined in the swagger-files of the relevant services"
      produces:
      - "application/json"
      responses:
        200:
          description: "Returns all model projects of the relevant services as array"
          schema:
            type: array
            items:
              $ref: "#/definitions/DomainModel"
        405:
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: "saveModelAppearance"
      tags:
        - "DomainModelBackend"
      parameters: 
      - in: body
        name: "models"
        description: "Model objects"
        required: true
        schema:
          type: "array"
          items:
            $ref: "#/definitions/DomainModel"
      
      summary: "Saves the appreance data of the model objects (headerColor, iconName, positionX, positionY). If any of the other properties of the model are changed, this will be ignored."
      produces:
      - "application/json"
      responses:
        200:
          description: "Save successful"
          schema:
            type: array
            items:
              $ref: '#/definitions/DomainModel'
        405:
          description: "Invalid input"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "Internal Server Error"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
    DomainModel:
      type: object
      required:
        - id
        - name
        - serviceName
        - properties
      properties:
        id:
          type: string
          description: unique id of the domain model
        name:
          type: string
          description: name of the model object
        serviceName:
          type: string
          description: name of the microservice the model belongs to
        properties:
          type: array
          items:
            $ref: "#/definitions/PropertyInfo"
        headerColor:
          type: string
          description: Specifies the color of the header (as valid html color)
          example: 
           - "#fcfcfc"
           - "goldenrod"
        iconName:
          type: string
          description: "Specifies the name of a google material icon which should be displayed on this model (optional). For full list see https://material.io/tools/icons/"
          example: bookmark_border
        positionX:
          type: integer
          description: "The horizontal position of the Model object on the viewport"
          example: 42
        positionY:
          type: integer
          description: "The vertical position of the Model object on the viewport"
          example: 37
        zIndex:
          type: integer
          description: "The z-index of the model in the viewport"
          example: 38472
    PropertyInfo:
      type: object
      required:
        - name
        - type
        - isArray
        - isRequired
      properties:
        name:
          type: string
          description: name of the property.
          example: property1
        type:
          type: string
          description: "Type of the property. Can be any primitive type defined in swagger spec or the name of another domain model"
          example: "string"
        isArray:
          type: boolean
          description: "Indicates if this property is an array"
          example: true
        isRequired:
          type: boolean
          description: "Indicates if this property is mandatory"
          example: false
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code: 
          type: string
          pattern: '^DMS-\d+$'
          description: "This error code should have the format 'DMS-XXX' where XXX is an integer. It is used to uniquely distinguish different error cases in order to display a suitable and translatable error message on the UI."
          example: "DMS-1234"
        message:
          type: string
          description: "Should contain a short, meaningful description of the error case. Might be displayed to the end user."
          example: "Could not create service 'some-name' because this service already exists."
